// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.port;

import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("port");
    public Optional<String> baseUrl() {
        return Codegen.stringProp("baseUrl").config(config).get();
    }
    public String clientId() {
        return Codegen.stringProp("clientId").config(config).require();
    }
    public String secret() {
        return Codegen.stringProp("secret").config(config).require();
    }
    public String token() {
        return Codegen.stringProp("token").config(config).require();
    }
}
