// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.port;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.dirien.port.EntityArgs;
import io.dirien.port.Utilities;
import io.dirien.port.inputs.EntityState;
import io.dirien.port.outputs.EntityProperty;
import io.dirien.port.outputs.EntityRelation;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="port:index/entity:Entity")
public class Entity extends com.pulumi.resources.CustomResource {
    /**
     * The blueprint identifier the entity relates to
     * 
     */
    @Export(name="blueprint", refs={String.class}, tree="[0]")
    private Output<String> blueprint;

    /**
     * @return The blueprint identifier the entity relates to
     * 
     */
    public Output<String> blueprint() {
        return this.blueprint;
    }
    @Export(name="createdAt", refs={String.class}, tree="[0]")
    private Output<String> createdAt;

    public Output<String> createdAt() {
        return this.createdAt;
    }
    @Export(name="createdBy", refs={String.class}, tree="[0]")
    private Output<String> createdBy;

    public Output<String> createdBy() {
        return this.createdBy;
    }
    /**
     * The identifier of the entity
     * 
     */
    @Export(name="identifier", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> identifier;

    /**
     * @return The identifier of the entity
     * 
     */
    public Output<Optional<String>> identifier() {
        return Codegen.optional(this.identifier);
    }
    /**
     * The metadata of the entity
     * 
     */
    @Export(name="properties", refs={List.class,EntityProperty.class}, tree="[0,1]")
    private Output<List<EntityProperty>> properties;

    /**
     * @return The metadata of the entity
     * 
     */
    public Output<List<EntityProperty>> properties() {
        return this.properties;
    }
    /**
     * The other entities that are connected
     * 
     */
    @Export(name="relations", refs={List.class,EntityRelation.class}, tree="[0,1]")
    private Output</* @Nullable */ List<EntityRelation>> relations;

    /**
     * @return The other entities that are connected
     * 
     */
    public Output<Optional<List<EntityRelation>>> relations() {
        return Codegen.optional(this.relations);
    }
    /**
     * The runID of the action run that created the entity
     * 
     */
    @Export(name="runId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> runId;

    /**
     * @return The runID of the action run that created the entity
     * 
     */
    public Output<Optional<String>> runId() {
        return Codegen.optional(this.runId);
    }
    /**
     * The team related to the entity
     * 
     */
    @Export(name="team", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> team;

    /**
     * @return The team related to the entity
     * 
     */
    public Output<Optional<String>> team() {
        return Codegen.optional(this.team);
    }
    /**
     * The teams related to the entity
     * 
     */
    @Export(name="teams", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> teams;

    /**
     * @return The teams related to the entity
     * 
     */
    public Output<Optional<List<String>>> teams() {
        return Codegen.optional(this.teams);
    }
    /**
     * The display name of the entity
     * 
     */
    @Export(name="title", refs={String.class}, tree="[0]")
    private Output<String> title;

    /**
     * @return The display name of the entity
     * 
     */
    public Output<String> title() {
        return this.title;
    }
    @Export(name="updatedAt", refs={String.class}, tree="[0]")
    private Output<String> updatedAt;

    public Output<String> updatedAt() {
        return this.updatedAt;
    }
    @Export(name="updatedBy", refs={String.class}, tree="[0]")
    private Output<String> updatedBy;

    public Output<String> updatedBy() {
        return this.updatedBy;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Entity(String name) {
        this(name, EntityArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Entity(String name, EntityArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Entity(String name, EntityArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("port:index/entity:Entity", name, args == null ? EntityArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private Entity(String name, Output<String> id, @Nullable EntityState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("port:index/entity:Entity", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Entity get(String name, Output<String> id, @Nullable EntityState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Entity(name, id, state, options);
    }
}
