# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .action import *
from .blueprint import *
from .entity import *
from .provider import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import ediri_port.config as __config
    config = __config
else:
    config = _utilities.lazy_import('ediri_port.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "port",
  "mod": "index/action",
  "fqn": "ediri_port",
  "classes": {
   "port:index/action:Action": "Action"
  }
 },
 {
  "pkg": "port",
  "mod": "index/blueprint",
  "fqn": "ediri_port",
  "classes": {
   "port:index/blueprint:Blueprint": "Blueprint"
  }
 },
 {
  "pkg": "port",
  "mod": "index/entity",
  "fqn": "ediri_port",
  "classes": {
   "port:index/entity:Entity": "Entity"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "port",
  "token": "pulumi:providers:port",
  "fqn": "ediri_port",
  "class": "Provider"
 }
]
"""
)
