// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.port.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class BlueprintRelation {
    private @Nullable String identifier;
    private @Nullable Boolean many;
    private @Nullable Boolean required;
    private String target;
    private String title;

    private BlueprintRelation() {}
    public Optional<String> identifier() {
        return Optional.ofNullable(this.identifier);
    }
    public Optional<Boolean> many() {
        return Optional.ofNullable(this.many);
    }
    public Optional<Boolean> required() {
        return Optional.ofNullable(this.required);
    }
    public String target() {
        return this.target;
    }
    public String title() {
        return this.title;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(BlueprintRelation defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String identifier;
        private @Nullable Boolean many;
        private @Nullable Boolean required;
        private String target;
        private String title;
        public Builder() {}
        public Builder(BlueprintRelation defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.identifier = defaults.identifier;
    	      this.many = defaults.many;
    	      this.required = defaults.required;
    	      this.target = defaults.target;
    	      this.title = defaults.title;
        }

        @CustomType.Setter
        public Builder identifier(@Nullable String identifier) {
            this.identifier = identifier;
            return this;
        }
        @CustomType.Setter
        public Builder many(@Nullable Boolean many) {
            this.many = many;
            return this;
        }
        @CustomType.Setter
        public Builder required(@Nullable Boolean required) {
            this.required = required;
            return this;
        }
        @CustomType.Setter
        public Builder target(String target) {
            this.target = Objects.requireNonNull(target);
            return this;
        }
        @CustomType.Setter
        public Builder title(String title) {
            this.title = Objects.requireNonNull(title);
            return this;
        }
        public BlueprintRelation build() {
            final var o = new BlueprintRelation();
            o.identifier = identifier;
            o.many = many;
            o.required = required;
            o.target = target;
            o.title = title;
            return o;
        }
    }
}
