// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.port.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class BlueprintChangelogDestination {
    private String type;
    private @Nullable String url;

    private BlueprintChangelogDestination() {}
    public String type() {
        return this.type;
    }
    public Optional<String> url() {
        return Optional.ofNullable(this.url);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(BlueprintChangelogDestination defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String type;
        private @Nullable String url;
        public Builder() {}
        public Builder(BlueprintChangelogDestination defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.type = defaults.type;
    	      this.url = defaults.url;
        }

        @CustomType.Setter
        public Builder type(String type) {
            this.type = Objects.requireNonNull(type);
            return this;
        }
        @CustomType.Setter
        public Builder url(@Nullable String url) {
            this.url = url;
            return this;
        }
        public BlueprintChangelogDestination build() {
            final var o = new BlueprintChangelogDestination();
            o.type = type;
            o.url = url;
            return o;
        }
    }
}
