// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.port.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class BlueprintProperty {
    private @Nullable String default_;
    private @Nullable List<String> defaultItems;
    private @Nullable String description;
    private @Nullable Map<String,String> enumColors;
    private @Nullable List<String> enums;
    private @Nullable String format;
    private @Nullable String icon;
    private String identifier;
    private @Nullable Boolean required;
    private @Nullable String spec;
    private String title;
    private String type;

    private BlueprintProperty() {}
    public Optional<String> default_() {
        return Optional.ofNullable(this.default_);
    }
    public List<String> defaultItems() {
        return this.defaultItems == null ? List.of() : this.defaultItems;
    }
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }
    public Map<String,String> enumColors() {
        return this.enumColors == null ? Map.of() : this.enumColors;
    }
    public List<String> enums() {
        return this.enums == null ? List.of() : this.enums;
    }
    public Optional<String> format() {
        return Optional.ofNullable(this.format);
    }
    public Optional<String> icon() {
        return Optional.ofNullable(this.icon);
    }
    public String identifier() {
        return this.identifier;
    }
    public Optional<Boolean> required() {
        return Optional.ofNullable(this.required);
    }
    public Optional<String> spec() {
        return Optional.ofNullable(this.spec);
    }
    public String title() {
        return this.title;
    }
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(BlueprintProperty defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String default_;
        private @Nullable List<String> defaultItems;
        private @Nullable String description;
        private @Nullable Map<String,String> enumColors;
        private @Nullable List<String> enums;
        private @Nullable String format;
        private @Nullable String icon;
        private String identifier;
        private @Nullable Boolean required;
        private @Nullable String spec;
        private String title;
        private String type;
        public Builder() {}
        public Builder(BlueprintProperty defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.default_ = defaults.default_;
    	      this.defaultItems = defaults.defaultItems;
    	      this.description = defaults.description;
    	      this.enumColors = defaults.enumColors;
    	      this.enums = defaults.enums;
    	      this.format = defaults.format;
    	      this.icon = defaults.icon;
    	      this.identifier = defaults.identifier;
    	      this.required = defaults.required;
    	      this.spec = defaults.spec;
    	      this.title = defaults.title;
    	      this.type = defaults.type;
        }

        @CustomType.Setter("default")
        public Builder default_(@Nullable String default_) {
            this.default_ = default_;
            return this;
        }
        @CustomType.Setter
        public Builder defaultItems(@Nullable List<String> defaultItems) {
            this.defaultItems = defaultItems;
            return this;
        }
        public Builder defaultItems(String... defaultItems) {
            return defaultItems(List.of(defaultItems));
        }
        @CustomType.Setter
        public Builder description(@Nullable String description) {
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder enumColors(@Nullable Map<String,String> enumColors) {
            this.enumColors = enumColors;
            return this;
        }
        @CustomType.Setter
        public Builder enums(@Nullable List<String> enums) {
            this.enums = enums;
            return this;
        }
        public Builder enums(String... enums) {
            return enums(List.of(enums));
        }
        @CustomType.Setter
        public Builder format(@Nullable String format) {
            this.format = format;
            return this;
        }
        @CustomType.Setter
        public Builder icon(@Nullable String icon) {
            this.icon = icon;
            return this;
        }
        @CustomType.Setter
        public Builder identifier(String identifier) {
            this.identifier = Objects.requireNonNull(identifier);
            return this;
        }
        @CustomType.Setter
        public Builder required(@Nullable Boolean required) {
            this.required = required;
            return this;
        }
        @CustomType.Setter
        public Builder spec(@Nullable String spec) {
            this.spec = spec;
            return this;
        }
        @CustomType.Setter
        public Builder title(String title) {
            this.title = Objects.requireNonNull(title);
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            this.type = Objects.requireNonNull(type);
            return this;
        }
        public BlueprintProperty build() {
            final var o = new BlueprintProperty();
            o.default_ = default_;
            o.defaultItems = defaultItems;
            o.description = description;
            o.enumColors = enumColors;
            o.enums = enums;
            o.format = format;
            o.icon = icon;
            o.identifier = identifier;
            o.required = required;
            o.spec = spec;
            o.title = title;
            o.type = type;
            return o;
        }
    }
}
