// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Port.Outputs
{

    [OutputType]
    public sealed class ActionInvocationMethod
    {
        public readonly bool? Agent;
        public readonly bool? OmitPayload;
        public readonly bool? OmitUserInputs;
        public readonly string? Org;
        public readonly string? Repo;
        public readonly bool? ReportWorkflowStatus;
        public readonly string Type;
        public readonly string? Url;
        public readonly string? Workflow;

        [OutputConstructor]
        private ActionInvocationMethod(
            bool? agent,

            bool? omitPayload,

            bool? omitUserInputs,

            string? org,

            string? repo,

            bool? reportWorkflowStatus,

            string type,

            string? url,

            string? workflow)
        {
            Agent = agent;
            OmitPayload = omitPayload;
            OmitUserInputs = omitUserInputs;
            Org = org;
            Repo = repo;
            ReportWorkflowStatus = reportWorkflowStatus;
            Type = type;
            Url = url;
            Workflow = workflow;
        }
    }
}
