// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Port.Outputs
{

    [OutputType]
    public sealed class ActionUserProperty
    {
        public readonly string? Blueprint;
        public readonly string? Default;
        public readonly ImmutableArray<string> DefaultItems;
        public readonly string? Description;
        public readonly ImmutableArray<string> Enums;
        public readonly string? Format;
        public readonly string Identifier;
        public readonly string? Pattern;
        public readonly bool? Required;
        public readonly string Title;
        public readonly string Type;

        [OutputConstructor]
        private ActionUserProperty(
            string? blueprint,

            string? @default,

            ImmutableArray<string> defaultItems,

            string? description,

            ImmutableArray<string> enums,

            string? format,

            string identifier,

            string? pattern,

            bool? required,

            string title,

            string type)
        {
            Blueprint = blueprint;
            Default = @default;
            DefaultItems = defaultItems;
            Description = description;
            Enums = enums;
            Format = format;
            Identifier = identifier;
            Pattern = pattern;
            Required = required;
            Title = title;
            Type = type;
        }
    }
}
