// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Port.Outputs
{

    [OutputType]
    public sealed class BlueprintChangelogDestination
    {
        public readonly string Type;
        public readonly string? Url;

        [OutputConstructor]
        private BlueprintChangelogDestination(
            string type,

            string? url)
        {
            Type = type;
            Url = url;
        }
    }
}
