// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Port.Outputs
{

    [OutputType]
    public sealed class BlueprintRelation
    {
        public readonly string? Identifier;
        public readonly bool? Many;
        public readonly bool? Required;
        public readonly string Target;
        public readonly string Title;

        [OutputConstructor]
        private BlueprintRelation(
            string? identifier,

            bool? many,

            bool? required,

            string target,

            string title)
        {
            Identifier = identifier;
            Many = many;
            Required = required;
            Target = target;
            Title = title;
        }
    }
}
