// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Port.Outputs
{

    [OutputType]
    public sealed class BlueprintCalculationProperty
    {
        public readonly string Calculation;
        public readonly bool? Colorized;
        public readonly ImmutableDictionary<string, string>? Colors;
        public readonly string? Description;
        public readonly string? Format;
        public readonly string? Icon;
        public readonly string Identifier;
        public readonly string? Title;
        public readonly string Type;

        [OutputConstructor]
        private BlueprintCalculationProperty(
            string calculation,

            bool? colorized,

            ImmutableDictionary<string, string>? colors,

            string? description,

            string? format,

            string? icon,

            string identifier,

            string? title,

            string type)
        {
            Calculation = calculation;
            Colorized = colorized;
            Colors = colors;
            Description = description;
            Format = format;
            Icon = icon;
            Identifier = identifier;
            Title = title;
            Type = type;
        }
    }
}
