// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Port.Inputs
{

    public sealed class ActionInvocationMethodGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("agent")]
        public Input<bool>? Agent { get; set; }

        [Input("omitPayload")]
        public Input<bool>? OmitPayload { get; set; }

        [Input("omitUserInputs")]
        public Input<bool>? OmitUserInputs { get; set; }

        [Input("org")]
        public Input<string>? Org { get; set; }

        [Input("repo")]
        public Input<string>? Repo { get; set; }

        [Input("reportWorkflowStatus")]
        public Input<bool>? ReportWorkflowStatus { get; set; }

        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        [Input("url")]
        public Input<string>? Url { get; set; }

        [Input("workflow")]
        public Input<string>? Workflow { get; set; }

        public ActionInvocationMethodGetArgs()
        {
        }
        public static new ActionInvocationMethodGetArgs Empty => new ActionInvocationMethodGetArgs();
    }
}
