// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Port.Inputs
{

    public sealed class BlueprintCalculationPropertyArgs : global::Pulumi.ResourceArgs
    {
        [Input("calculation", required: true)]
        public Input<string> Calculation { get; set; } = null!;

        [Input("colorized")]
        public Input<bool>? Colorized { get; set; }

        [Input("colors")]
        private InputMap<string>? _colors;
        public InputMap<string> Colors
        {
            get => _colors ?? (_colors = new InputMap<string>());
            set => _colors = value;
        }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("format")]
        public Input<string>? Format { get; set; }

        [Input("icon")]
        public Input<string>? Icon { get; set; }

        [Input("identifier", required: true)]
        public Input<string> Identifier { get; set; } = null!;

        [Input("title")]
        public Input<string>? Title { get; set; }

        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public BlueprintCalculationPropertyArgs()
        {
        }
        public static new BlueprintCalculationPropertyArgs Empty => new BlueprintCalculationPropertyArgs();
    }
}
