// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Port.Inputs
{

    public sealed class BlueprintRelationGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("identifier")]
        public Input<string>? Identifier { get; set; }

        [Input("many")]
        public Input<bool>? Many { get; set; }

        [Input("required")]
        public Input<bool>? Required { get; set; }

        [Input("target", required: true)]
        public Input<string> Target { get; set; } = null!;

        [Input("title", required: true)]
        public Input<string> Title { get; set; } = null!;

        public BlueprintRelationGetArgs()
        {
        }
        public static new BlueprintRelationGetArgs Empty => new BlueprintRelationGetArgs();
    }
}
