// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.port.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import io.dirien.port.inputs.ActionInvocationMethodArgs;
import io.dirien.port.inputs.ActionUserPropertyArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ActionState extends com.pulumi.resources.ResourceArgs {

    public static final ActionState Empty = new ActionState();

    /**
     * The identifier of the blueprint
     * 
     */
    @Import(name="blueprintIdentifier")
    private @Nullable Output<String> blueprintIdentifier;

    /**
     * @return The identifier of the blueprint
     * 
     */
    public Optional<Output<String>> blueprintIdentifier() {
        return Optional.ofNullable(this.blueprintIdentifier);
    }

    /**
     * The description of the action
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return The description of the action
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * The icon of the action
     * 
     */
    @Import(name="icon")
    private @Nullable Output<String> icon;

    /**
     * @return The icon of the action
     * 
     */
    public Optional<Output<String>> icon() {
        return Optional.ofNullable(this.icon);
    }

    /**
     * The identifier of the action
     * 
     */
    @Import(name="identifier")
    private @Nullable Output<String> identifier;

    /**
     * @return The identifier of the action
     * 
     */
    public Optional<Output<String>> identifier() {
        return Optional.ofNullable(this.identifier);
    }

    /**
     * The methods the action is dispatched in. Supports WEBHOOK, KAFKA and GITHUB
     * 
     */
    @Import(name="invocationMethod")
    private @Nullable Output<ActionInvocationMethodArgs> invocationMethod;

    /**
     * @return The methods the action is dispatched in. Supports WEBHOOK, KAFKA and GITHUB
     * 
     */
    public Optional<Output<ActionInvocationMethodArgs>> invocationMethod() {
        return Optional.ofNullable(this.invocationMethod);
    }

    /**
     * The display name of the action
     * 
     */
    @Import(name="title")
    private @Nullable Output<String> title;

    /**
     * @return The display name of the action
     * 
     */
    public Optional<Output<String>> title() {
        return Optional.ofNullable(this.title);
    }

    /**
     * The type of the action, one of CREATE, DAY-2, DELETE
     * 
     */
    @Import(name="trigger")
    private @Nullable Output<String> trigger;

    /**
     * @return The type of the action, one of CREATE, DAY-2, DELETE
     * 
     */
    public Optional<Output<String>> trigger() {
        return Optional.ofNullable(this.trigger);
    }

    /**
     * The input properties of the action
     * 
     */
    @Import(name="userProperties")
    private @Nullable Output<List<ActionUserPropertyArgs>> userProperties;

    /**
     * @return The input properties of the action
     * 
     */
    public Optional<Output<List<ActionUserPropertyArgs>>> userProperties() {
        return Optional.ofNullable(this.userProperties);
    }

    private ActionState() {}

    private ActionState(ActionState $) {
        this.blueprintIdentifier = $.blueprintIdentifier;
        this.description = $.description;
        this.icon = $.icon;
        this.identifier = $.identifier;
        this.invocationMethod = $.invocationMethod;
        this.title = $.title;
        this.trigger = $.trigger;
        this.userProperties = $.userProperties;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ActionState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ActionState $;

        public Builder() {
            $ = new ActionState();
        }

        public Builder(ActionState defaults) {
            $ = new ActionState(Objects.requireNonNull(defaults));
        }

        /**
         * @param blueprintIdentifier The identifier of the blueprint
         * 
         * @return builder
         * 
         */
        public Builder blueprintIdentifier(@Nullable Output<String> blueprintIdentifier) {
            $.blueprintIdentifier = blueprintIdentifier;
            return this;
        }

        /**
         * @param blueprintIdentifier The identifier of the blueprint
         * 
         * @return builder
         * 
         */
        public Builder blueprintIdentifier(String blueprintIdentifier) {
            return blueprintIdentifier(Output.of(blueprintIdentifier));
        }

        /**
         * @param description The description of the action
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description The description of the action
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param icon The icon of the action
         * 
         * @return builder
         * 
         */
        public Builder icon(@Nullable Output<String> icon) {
            $.icon = icon;
            return this;
        }

        /**
         * @param icon The icon of the action
         * 
         * @return builder
         * 
         */
        public Builder icon(String icon) {
            return icon(Output.of(icon));
        }

        /**
         * @param identifier The identifier of the action
         * 
         * @return builder
         * 
         */
        public Builder identifier(@Nullable Output<String> identifier) {
            $.identifier = identifier;
            return this;
        }

        /**
         * @param identifier The identifier of the action
         * 
         * @return builder
         * 
         */
        public Builder identifier(String identifier) {
            return identifier(Output.of(identifier));
        }

        /**
         * @param invocationMethod The methods the action is dispatched in. Supports WEBHOOK, KAFKA and GITHUB
         * 
         * @return builder
         * 
         */
        public Builder invocationMethod(@Nullable Output<ActionInvocationMethodArgs> invocationMethod) {
            $.invocationMethod = invocationMethod;
            return this;
        }

        /**
         * @param invocationMethod The methods the action is dispatched in. Supports WEBHOOK, KAFKA and GITHUB
         * 
         * @return builder
         * 
         */
        public Builder invocationMethod(ActionInvocationMethodArgs invocationMethod) {
            return invocationMethod(Output.of(invocationMethod));
        }

        /**
         * @param title The display name of the action
         * 
         * @return builder
         * 
         */
        public Builder title(@Nullable Output<String> title) {
            $.title = title;
            return this;
        }

        /**
         * @param title The display name of the action
         * 
         * @return builder
         * 
         */
        public Builder title(String title) {
            return title(Output.of(title));
        }

        /**
         * @param trigger The type of the action, one of CREATE, DAY-2, DELETE
         * 
         * @return builder
         * 
         */
        public Builder trigger(@Nullable Output<String> trigger) {
            $.trigger = trigger;
            return this;
        }

        /**
         * @param trigger The type of the action, one of CREATE, DAY-2, DELETE
         * 
         * @return builder
         * 
         */
        public Builder trigger(String trigger) {
            return trigger(Output.of(trigger));
        }

        /**
         * @param userProperties The input properties of the action
         * 
         * @return builder
         * 
         */
        public Builder userProperties(@Nullable Output<List<ActionUserPropertyArgs>> userProperties) {
            $.userProperties = userProperties;
            return this;
        }

        /**
         * @param userProperties The input properties of the action
         * 
         * @return builder
         * 
         */
        public Builder userProperties(List<ActionUserPropertyArgs> userProperties) {
            return userProperties(Output.of(userProperties));
        }

        /**
         * @param userProperties The input properties of the action
         * 
         * @return builder
         * 
         */
        public Builder userProperties(ActionUserPropertyArgs... userProperties) {
            return userProperties(List.of(userProperties));
        }

        public ActionState build() {
            return $;
        }
    }

}
