// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.port.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class BlueprintRelationArgs extends com.pulumi.resources.ResourceArgs {

    public static final BlueprintRelationArgs Empty = new BlueprintRelationArgs();

    @Import(name="identifier")
    private @Nullable Output<String> identifier;

    public Optional<Output<String>> identifier() {
        return Optional.ofNullable(this.identifier);
    }

    @Import(name="many")
    private @Nullable Output<Boolean> many;

    public Optional<Output<Boolean>> many() {
        return Optional.ofNullable(this.many);
    }

    @Import(name="required")
    private @Nullable Output<Boolean> required;

    public Optional<Output<Boolean>> required() {
        return Optional.ofNullable(this.required);
    }

    @Import(name="target", required=true)
    private Output<String> target;

    public Output<String> target() {
        return this.target;
    }

    @Import(name="title", required=true)
    private Output<String> title;

    public Output<String> title() {
        return this.title;
    }

    private BlueprintRelationArgs() {}

    private BlueprintRelationArgs(BlueprintRelationArgs $) {
        this.identifier = $.identifier;
        this.many = $.many;
        this.required = $.required;
        this.target = $.target;
        this.title = $.title;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(BlueprintRelationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private BlueprintRelationArgs $;

        public Builder() {
            $ = new BlueprintRelationArgs();
        }

        public Builder(BlueprintRelationArgs defaults) {
            $ = new BlueprintRelationArgs(Objects.requireNonNull(defaults));
        }

        public Builder identifier(@Nullable Output<String> identifier) {
            $.identifier = identifier;
            return this;
        }

        public Builder identifier(String identifier) {
            return identifier(Output.of(identifier));
        }

        public Builder many(@Nullable Output<Boolean> many) {
            $.many = many;
            return this;
        }

        public Builder many(Boolean many) {
            return many(Output.of(many));
        }

        public Builder required(@Nullable Output<Boolean> required) {
            $.required = required;
            return this;
        }

        public Builder required(Boolean required) {
            return required(Output.of(required));
        }

        public Builder target(Output<String> target) {
            $.target = target;
            return this;
        }

        public Builder target(String target) {
            return target(Output.of(target));
        }

        public Builder title(Output<String> title) {
            $.title = title;
            return this;
        }

        public Builder title(String title) {
            return title(Output.of(title));
        }

        public BlueprintRelationArgs build() {
            $.target = Objects.requireNonNull($.target, "expected parameter 'target' to be non-null");
            $.title = Objects.requireNonNull($.title, "expected parameter 'title' to be non-null");
            return $;
        }
    }

}
