// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.port.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class EntityRelationArgs extends com.pulumi.resources.ResourceArgs {

    public static final EntityRelationArgs Empty = new EntityRelationArgs();

    @Import(name="identifier", required=true)
    private Output<String> identifier;

    public Output<String> identifier() {
        return this.identifier;
    }

    @Import(name="name", required=true)
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }

    private EntityRelationArgs() {}

    private EntityRelationArgs(EntityRelationArgs $) {
        this.identifier = $.identifier;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(EntityRelationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private EntityRelationArgs $;

        public Builder() {
            $ = new EntityRelationArgs();
        }

        public Builder(EntityRelationArgs defaults) {
            $ = new EntityRelationArgs(Objects.requireNonNull(defaults));
        }

        public Builder identifier(Output<String> identifier) {
            $.identifier = identifier;
            return this;
        }

        public Builder identifier(String identifier) {
            return identifier(Output.of(identifier));
        }

        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public EntityRelationArgs build() {
            $.identifier = Objects.requireNonNull($.identifier, "expected parameter 'identifier' to be non-null");
            $.name = Objects.requireNonNull($.name, "expected parameter 'name' to be non-null");
            return $;
        }
    }

}
